/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.ProjetoController;
import java.awt.Color;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.Projeto;
import tools.Combos;
import tools.*;

/**
 *
 * @author jonasdhein
 */
public class ProjetoView extends javax.swing.JFrame {

    /**
     * Creates new form ViewAlunos
     */
    Projeto objProjeto;
    Combos cbCidade;
    
    public ProjetoView() {
        initComponents();
        
        try{
            
           //CARREGAR CIDADES EXISTENTES
            atualizarTabela();
            
            limparTela();
            
            this.getContentPane().setBackground(Color.WHITE);
            
            //SETA A BARRA LATERAL DA JTABLE
            jScrollPane2.setViewportView(jtbProjeto);

                        
        }catch(Exception ex){
            System.out.println("Erro ao atualizar os dados inicias da tela");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tppessoagroup = new javax.swing.ButtonGroup();
        lbldtfim = new javax.swing.JLabel();
        lblequipe = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbProjeto = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtNome = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblDescricao = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        txtdtinicio = new javax.swing.JFormattedTextField();
        lblinicio = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        txtdtfim = new javax.swing.JFormattedTextField();
        lblNome = new javax.swing.JLabel();
        lblvalor = new javax.swing.JLabel();
        txtvalor = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lbldtfim.setText("Data Fim:");

        lblequipe.setText("Equipe:");

        lblCodigo.setText("Código:");

        jtbProjeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbProjeto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtbProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbProjetoMouseClicked(evt);
            }
        });
        jtbProjeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbProjetoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtbProjeto);

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sign-add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sign-delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/device-computer.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Projetos");

        lblDescricao.setText("Descrição:");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane3.setViewportView(txtDescricao);

        txtdtinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdtinicioActionPerformed(evt);
            }
        });

        lblinicio.setText("Data Incio:");

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sign-right.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtdtfim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdtfimActionPerformed(evt);
            }
        });

        lblNome.setText("Nome:");

        lblvalor.setText("Valor:");

        txtvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCodigo)
                                            .addComponent(txtdtinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblinicio))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblNome)
                                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblequipe)
                                                .addGap(26, 26, 26))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtdtfim, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbldtfim))
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblvalor)
                                                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(lblDescricao))
                                .addGap(138, 138, 138)))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(lblNome)
                    .addComponent(lblequipe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinicio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldtfim)
                            .addComponent(lblvalor))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtdtinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdtfim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jtbProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbProjetoMouseClicked
        // TODO add your handling code here:
        //pega a linha selecionada
         int linhaSelecionada = jtbProjeto.getSelectedRow();
         // Primeira coluna da linha que é o código
         String coluna1 = jtbProjeto.getModel().getValueAt(linhaSelecionada, 0).toString();
         //System.out.println(coluna1);
         objProjeto = new Projeto();
         ProjetoController objProjetoCon = new ProjetoController(objProjeto, null);
         objProjeto = objProjetoCon.buscar(coluna1);
         
         preencheCampos(); 
    }//GEN-LAST:event_jtbProjetoMouseClicked

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
     
        
        if (validarDados() == true) {
            //PREENCHE O OBJETO Projeto
            guardarDados();

             ProjetoController objProjetoCon = new ProjetoController(objProjeto, null);
            try {
                if (objProjetoCon.incluir() == true) {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Projeto incluido com sucesso!");
                    atualizarTabela();
                } else {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao incluir Projeto!");
                }
            } catch (Exception ex) {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
            }

            limparTela();
        } else {
              CaixaDeDialogo.obterinstancia().exibirMensagem("Preencha os dados corretamente!");
              return;
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            
        if (validarLinha() == true) {
        
            if(validarDados() == true){

                guardarDados();

                ProjetoController objProjetoCon = new ProjetoController(objProjeto, null);
                if (objProjetoCon.alterar() == true) {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Projeto alterado com Sucesso!");
                    atualizarTabela();
                } else {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao alterar Projeto");
                }

                limparTela();
                } else {
              CaixaDeDialogo.obterinstancia().exibirMensagem("Preencha os dados corretamente!");
              return;
                  }
                }

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       if (validarLinha() == true) {
         boolean pergunta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Você realmente deseja remover este registro?", "Atenção", 'p');
         if (pergunta == true) {
       String codprojeto = txtCodigo.getText();
       ProjetoController objProjetoCon = new ProjetoController(null, null);
        try {
            if (objProjetoCon.excluir(codprojeto) == true) {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Projeto removido com Sucesso!");
                atualizarTabela();
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao remover Projeto!");
            }
        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
       }
        limparTela();
         } else {
           return;
       }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jtbProjetoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbProjetoKeyPressed
        // TODO add your handling code here:
         jtbProjetoMouseClicked(null);
    }//GEN-LAST:event_jtbProjetoKeyPressed

    private void txtdtfimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdtfimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdtfimActionPerformed

    private void txtdtinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdtinicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdtinicioActionPerformed

    private void txtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalorActionPerformed

     private void limparTela() {
        try {
            //BLOQUEIA A ALTERAÇÃO DO CAMPO CÓDIGO
            txtCodigo.setEditable(false);
            
            //LIMPAR OS CAMPOS DA TELA

            txtdtfim.setFormatterFactory(null);
            
            txtCodigo.setText("");
            Formatacao.colocaMascara(txtdtfim, "##/##/####");
            Formatacao.colocaMascara(txtdtinicio, "##/##/####");
            txtNome.setText("");
            txtDescricao.setText("");
            txtdtinicio.setText("");
            txtNome.grabFocus();
            
            
    
            tppessoagroup.clearSelection();
  

 
            tppessoagroup.clearSelection();
            
            
        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
    }

     private void atualizarTabela() {
           try{
            
            ProjetoController objProjetoCon = new ProjetoController(null, jtbProjeto);
            objProjetoCon.preencheProjeto();
            
        }catch(Exception ex){
            System.out.println("Erro ao atualizar os dados inicias da tela");
        }
     }
     
      private boolean validarLinha () {
      int linha = jtbProjeto.getSelectedRow();
      
      try {
        if (linha<0) {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Selecione uma linha!");
           return false;
            }    
      } catch (Exception ex) {
          CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
      }
      
      return true;
  }
      
        private void guardarDados() {
        try {           
            if (objProjeto == null) {
                objProjeto = new Projeto();
            }
            
            objProjeto.setNmProjeto(txtNome.getText().toUpperCase());
            objProjeto.setDsProjeto(txtDescricao.getText());
            String datainicioformat = Formatacao.ajustaDataAMD(txtdtinicio.getText());
            objProjeto.setDtIncio(datainicioformat);
            String datafimformat = Formatacao.ajustaDataAMD(txtdtfim.getText());
            objProjeto.setDtFim(datafimformat);


            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Problemas no guardaDados: " + ex.getMessage());
        }
    }
        
         private void preencheCampos() {
        try {
            
            txtCodigo.setText(String.valueOf(objProjeto.getCodProjeto()));
            txtNome.setText(objProjeto.getNmProjeto());
            txtDescricao.setText(objProjeto.getDsProjeto());
            
 
        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro no prencheCampos " + ex.getMessage());
        }
    }
         
     private boolean validarDados() {
        try {   
          if(    
             //VALIDA OS CAMPOS DA TELA     

             txtNome.getText().trim().equals("") ||
             txtDescricao.getText().trim().equals("")) {

                                   
             return false;
           }

           
            return true;
        } catch (Exception ex) {
            //RETURN FALSE SE ALGUM CAMPO NAO ESTA PREENCHIDO CORRETAMENTE
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
            return false;
        }
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtbProjeto;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lbldtfim;
    private javax.swing.JLabel lblequipe;
    private javax.swing.JLabel lblinicio;
    private javax.swing.JLabel lblvalor;
    private javax.swing.ButtonGroup tppessoagroup;
    private javax.swing.JFormattedTextField txtCodigo;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JFormattedTextField txtNome;
    private javax.swing.JFormattedTextField txtdtfim;
    private javax.swing.JFormattedTextField txtdtinicio;
    private javax.swing.JFormattedTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
